spring:
  task:
    scheduling:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
app:
  security:
    jwt-secret: ${JWT_SECRET}
    internal-api-key: test-internal-key
